config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    #get  '/users' => 'home_page#home'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end





  root to: 'home_page#home'
  namespace :api, defaults:{ format: :json }do
      namespace :v1 do
        resources :products, :only => [:show,:index]
        resources :category_has_products, :only => [:show,:index]
      end
    end

  #  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  #devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope "(:locale)",locale:/#{I18n.available_locales.join("|")}/ do

  #  devise_scope :user do
  #      delete '/users/sign_out' => 'devise/sessions#destroy'
  #  end


    resources :category, except:[:delete] do
      collection do
        get 'show', to: :show
      end
      resources :product, only:[]  do
        collection do
          get 'showall', to: :showall
          get 'newest', to: :newest
          get 'pricelow', to: :pricelow
          get 'pricehigh', to: :pricehigh
        end
      end
      #resources :user do
      #  collection do
      #    get '/users/sign_out' => 'devise/sessions#destroy'
      #  end
      #end
    end

    resources :product, only:[]  do
      member do
        get 'show', to: :show
      end
    end

    resources :review, only: [] do
      collection do
        get 'create', to: :create
      end
    end

    scope 'admin' do
      resources :product do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          post 'change', to: :change
          get 'list', to: :list
          get 'status', to: :status
          get 'showimage', to: :showimage
          post 'sortimages', to: :sortimages
        end
      end
    end
    #assert_generates '../category/status', controller: 'category', action: 'status'
    scope 'admin' do
      resources :category do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          get 'list', to: :list
          get 'status', to: :status
          post 'change', to: :change
        end
      end
      resources :product_images do
         collection do
           post 'create', to: :create
           post 'createExisting', to: :createExisting
           post 'updateorder', to: :updateorder
         end
      end
    end

    post 'addtocart', to: 'application#addtocart'
    get 'addtocartget', to: 'application#addtocartget'
    get 'refreshcart', to: 'shop#refreshcart'


    resources :checkout, only: [] do
      collection do
        get 'index', to: :index
        get 'first', to: :first
        post 'first_data', to: :first
        get 'second', to: :second
        post 'second_data', to: :second_data
        get 'cart', to: :cart
        get 'deletecart', to: :deletecart
      end
    end

    resources :category, only: [] do
      resources :product, only: [] do
        collection do
          get 'showforcategory', to: :showforcategory
        end
      end
    end

    get 'home', to: 'home_page#home'
    get 'team', to: 'hometeam#index'
    get 'admin/index', to: 'admin#admin_index'

    resources :admin do
      collection do
        get 'userlist', to: :user
        get 'beadmin', to: :beadmin
        get 'removeadmin', to: :removeadmin
      end
    end
    resources :product_images
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  belongs_to :country
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  has_many :line_product
  has_one :order
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product, through: :categoryHasProduct
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :address
  has_many :order
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :couponUse
end

app/models/coupon_use.rb
class CouponUse < ApplicationRecord
  belongs_to :customer
  has_one :coupon
  has_one :order
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :order
  has_many :cart
  has_many :couponUse
  has_many :address
  has_many :customerTransaction
  has_one :user
end

app/models/line_product.rb
class LineProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :OrderStatus
  belongs_to :country
  belongs_to :customer
  belongs_to :cart
  belongs_to :confirmation_order
  has_one :return
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :categories, through: :categoryHasProduct
  has_many :product_images
  has_many :reviews
  has_one :return
end

app/models/product_discount.rb
class ProductDiscount < ApplicationRecord
  belongs_to :product
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ImageUploader
  validates_processing_of :image
  validate :image_size_validation

  
  private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end

end

app/models/return.rb
class Return < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #before_action :authenticate_user!
#  before_create :generate_authentication_token!
  #before_filter :authenticate_user!
  has_many :review
  belongs_to :customer, optional: true



  def self.find_for_facebook_oauth(auth)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    # The User was found in our database
    return user if user
    # Check if the User is already registered without Facebook
    user = User.where(email: auth.info.email).first
    return user if user
    user = User.new(
         name: auth.extra.raw_info.name,
         provider: auth.provider, uid: auth.uid,
         email: auth.info.email,
         password: Devise.friendly_token[0,20])
    user.skip_confirmation!
    user.save
    user
   end

#=end
#  def self.create_with_omniauth(auth)
  #  create! do |user|
#      user.provider = auth["provider"]
#      user.uid = auth["uid"]
#      user.name = auth["info"]["name"]
#    end
#  end


#  private
  #  def generate_authentication_token!#
  #      begin
  #      self.auth_token = Devise.friendly_token
    #  end while self.class.exists?(auth_token: auth_token)
  #  end


    def admin?
      self.role == 53
    end

    def linguist?
      self.role == 7
    end


end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def home
  end
end

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_error_messages!
    flash_alerts = []
    error_key = 'errors.messages.not_saved'

    if !flash.empty?
      flash_alerts.push(flash[:error]) if flash[:error]
      flash_alerts.push(flash[:alert]) if flash[:alert]
      flash_alerts.push(flash[:notice]) if flash[:notice]
      error_key = 'devise.failure.invalid'
    end

    return "" if resource.errors.empty? && flash_alerts.empty?
    errors = resource.errors.empty? ? flash_alerts : resource.errors.full_messages

    messages = errors.map { |msg| content_tag(:li, msg) }.join
    #sentence = I18n.t(error_key, :count    => errors.count,
    #                             :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="messages" id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

app/helpers/hometeam_helper.rb
module HometeamHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home_page/OLDhome.html.erb
<div>
	<section>
		<input type="radio" name="slider-select-element" id="img1" checked="checked"/>
		<input type="radio" name="slider-select-element" id="img2"/>
		<input type="radio" name="slider-select-element" id="img3"/>
		<input type="radio" name="slider-select-element" id="img4"/>
		<div id="slider-container">
			<div id="slider-box">
				<div class="slider-element">
					<%= image_tag("shop/b1.jpg", class: "img-responsive") %>
				</div>
				<div class="slider-element">
					<%= image_tag("shop/b2.jpg", class: "img-responsive") %>
				</div>
				<div class="slider-element">
					<%= image_tag("shop/b3.jpg", class: "img-responsive") %>
				</div>
				<div class="slider-element">
					<%= image_tag("shop/b4.jpg", class: "img-responsive") %>
				</div>
			</div>
		</div>
		<div id="slider-arrows">
			<label for="img1">O</label>
			<label for="img2">O</label>
			<label for="img3">O</label>
			<label for="img4">O</label>
		</div>
	</section>
</div>
<div class="container">
	<h1 class="home">WHY OUR WAYUU TEAM?</h1>
	<p id="lessText" class="home">
		Wayuu Mochila Bags are for every day, every outfit, and every personality! These handmade pieces of art will surely be the most unique bags you’ll come across in the world. The indigenous people that make them treat each piece as a canvas bringing out their passion and heart into each piece they create.<span><a id="seeMoreLink" class="text-link" href="" onclick="seeMore(); return false;"> ...See More</a></span>
	</p>
	<p id="moreText" class="home">
		Wayuu Mochila Bags are for every day, every outfit, and every personality! These handmade pieces of art will surely be the most unique bags you’ll come across in the world. The indigenous people that make them treat each piece as a canvas bringing out their passion and heart into each piece they create. Their skill and creativity will certainly impress men and women of all ages across many different cultures. Our goal is to share the beauty of the bags with the world as we bring awareness of the Wayuu people of Colombia. This will surely help to preserve their culture for many generations to come! In a short period of time, we have gone from an idea to actually putting something really fun and exciting together as we have been actively traveling and interacting with the Wayuu culture. It truly has been quite an exciting adventure our team has been on thus far. We have already employed people from different regions of Colombia and the United States. Striving for rapid growth while also creating an amazing company is something we work hard for each day. Bringing you the highest quality Wayuu Mochila Bags is something I know we can promise! We know with your support that our company will grow rapidly for many years to come. When you buy a bag you know you are helping many people along the way across multiple countries. A humanitarian way of producing a quality product for our customers is something our team has created. As of today, we are shipping worldwide and are reaching customers internationally. Be different, be unique, be Wayuu!<br><br>
		<i>Brandon Miller, Founder of Wayuu-Mochila-Bags.com</i><span><a id="seeLessLink" class="text-link" href="" onclick="seeLess(); return false;">See Less</a></span>
	</p>		
</div>

app/views/home_page/home.html.erb
<!-- *** HOMEPAGE CAROUSEL *** -->
<section>
	<div class="home-carousel">
		<div class="dark-mask"></div>
		<div class="container">
			<div class="homepage owl-carousel">
				<div class="item">
					<div class="row custom-row-carousel">
						<%= image_tag("shop/b1.jpg", class: "img-responsive margin-auto") %>
					</div>
				</div>
				<div class="item">
					<div class="row custom-row-carousel">
						<%= image_tag("shop/b2.jpg", class: "img-responsive margin-auto") %>
					</div>
				</div>
				<div class="item">
					<div class="row custom-row-carousel">
						<%= image_tag("shop/b3.jpg", class: "img-responsive margin-auto") %>
					</div>
				</div>
				<div class="item">
					<div class="row custom-row-carousel">
						<%= image_tag("shop/b4.jpg", class: "img-responsive margin-auto") %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- *** HOMEPAGE CAROUSEL END *** -->
<!-- *** HOME WAYUU TEXT *** -->
<section class="bar background-white no-mb">
	<div class="container">
		<div class="col-md-12">
			<div class="heading text-center">
				<h2><%=t(".why")%></h2>
			</div>
			<p id="lessText" class="lead text-center"><%=t('.desc1')%><a id="seeMoreLink" class="accent" href="" onclick="seeMore(); return false;"> ...See More</a>
			</p>
			<p id="moreText" class="lead text-center"><%=t('.desc2')%><br><br><i>Brandon Miller, Founder of Wayuu-Mochila-Bags.com</i><span><a id="seeLessLink" class="accent" href="" onclick="seeLess(); return false;">See Less</a></span>
			</p>
		</div>
	</div>
</section>
<!-- *** HOME WAYUU TEXT END *** -->
<!-- *** SHOP NOW *** -->
<section class="bar background-image-fixed-2 no-mb color-white text-center">
	<div class="dark-mask"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h3 class="text-uppercase"><%=t(".supplier")%></h3>
				<p class="text-center">
					<a href="#" class="btn btn-template-transparent-black btn-lg">SHOP NOW</a>
				</p>
			</div>
		</div>
	</div>
</section>
<!-- *** SHOP NOW END *** -->
<!-- *** BLOG *** -->
<section class="bar background-white no-mb">
	<div class="container">
		<div class="col-md-12">
			<div class="heading text-center">
				<h2>WAYUU BLOG</h2>
			</div>
			<p class="lead text-center"><%=t(".wayuu_blog1")%> <span class="accent">Check our blog!</span>
			</p>
			<!-- *** BLOG HOMEPAGE *** -->
			<div class="row">
				<div class="col-md-3 col-sm-6">
					<div class="box-image-text blog">
						<div class="top">
							<div class="image">
									<%= image_tag("shop/img/portfolio-4.jpg",alt:" ", class: "img-responsive margin-auto") %>
								<!-- <img src="img/portfolio-4.jpg" alt="" class="img-responsive"> -->
							</div>
							<div class="bg"></div>
							<div class="text">
								<p class="buttons">
									<a href="blog-post.html" class="btn btn-template-transparent-primary"><i class="fa fa-link"></i> Read more</a>
								</p>
							</div>
						</div>
						<div class="content">
							<h4><a href="blog-post.html">Fashion now</a></h4>
							<p class="author-category">By <a href="#">John Snow</a> in <a href="blog.html">Webdesign</a>
							</p>
							<p class="intro">Fifth abundantly made Give sixth hath. Cattle creature i be don't them behold green moved fowl Moved life us beast good yielding. Have bring.</p>
							<p class="read-more"><a href="blog-post.html" class="btn btn-template-main">Continue reading</a>
							</p>
						</div>
					</div>
					<!-- /.box-image-text -->
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="box-image-text blog">
						<div class="top">
							<div class="image">
							<%= image_tag("shop/img/portfolio-3.jpg",alt:" ", class: "img-responsive margin-auto") %>
							</div>
							<div class="bg"></div>
							<div class="text">
								<p class="buttons">
									<a href="blog-post.html" class="btn btn-template-transparent-primary"><i class="fa fa-link"></i> Read more</a>
								</p>
							</div>
						</div>
						<div class="content">
							<h4><a href="blog-post.html">Fashion now</a></h4>
							<p class="author-category">By <a href="#">John Snow</a> in <a href="blog.html">Webdesign</a>
							</p>
							<p class="intro">Fifth abundantly made Give sixth hath. Cattle creature i be don't them behold green moved fowl Moved life us beast good yielding. Have bring.</p>
							<p class="read-more"><a href="blog-post.html" class="btn btn-template-main">Continue reading</a>
							</p>
						</div>
					</div>
					<!-- /.box-image-text -->
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="box-image-text blog">
						<div class="top">
							<div class="image">
								<%= image_tag("shop/img/portfolio-5.jpg",alt:" ", class: "img-responsive margin-auto") %>
							</div>
							<div class="bg"></div>
							<div class="text">
								<p class="buttons">
									<a href="blog-post.html" class="btn btn-template-transparent-primary"><i class="fa fa-link"></i> Read more</a>
								</p>
							</div>
						</div>
						<div class="content">
							<h4><a href="blog-post.html">What to do</a></h4>
							<p class="author-category">By <a href="#">John Snow</a> in <a href="blog.html">Webdesign</a>
							</p>
							<p class="intro">Fifth abundantly made Give sixth hath. Cattle creature i be don't them behold green moved fowl Moved life us beast good yielding. Have bring.</p>
							<p class="read-more"><a href="blog-post.html" class="btn btn-template-main">Continue reading</a>
							</p>
						</div>
					</div>
					<!-- /.box-image-text -->
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="box-image-text blog">
						<div class="top">
							<div class="image">
								<%= image_tag("shop/img/portfolio-6.jpg",alt:" ", class: "img-responsive margin-auto") %>
							</div>
							<div class="bg"></div>
							<div class="text">
								<p class="buttons">
									<a href="blog-post.html" class="btn btn-template-transparent-primary"><i class="fa fa-link"></i> Read more</a>
								</p>
							</div>
						</div>
						<div class="content">
							<h4><a href="blog-post.html">5 ways to look awesome</a></h4>
							<p class="author-category">By <a href="#">John Snow</a> in <a href="blog.html">Webdesign</a>
							</p>
							<p class="intro">Am terminated it excellence invitation projection as. She graceful shy believed distance use nay. Lively is people.</p>
							<p class="read-more"><a href="blog-post.html" class="btn btn-template-main">Continue reading</a>
							</p>
						</div>
					</div>
					<!-- /.box-image-text -->
				</div>
			</div>
			<!-- /.row -->
			<!-- *** BLOG HOMEPAGE END *** -->
		</div>
	</div>
	<!-- /.container -->
</section>
<!-- *** BLOG END *** -->
<!-- *** MAIL *** -->
<section class="bar background-pentagon no-mb">
	<div class="container text-center">
		<div class="row text-center">
			<div class="col-md-12">
				<h1><%=t(".getInTouch")%></h1>
				<p class="lead accent"><%=t(".to_help")%></p>
			</div>
			<div class="col-md-8 col-md-offset-2">
				<form>
					<div class="row">
						<div class="col-sm-6">
							<div class="form-group">
								<label for="firstname"><%=t(".name")%></label>
								<input type="text" class="form-control" id="firstname">
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="lastname"><%=t(".last_name")%></label>
								<input type="text" class="form-control" id="lastname">
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="email"><%=t(".email")%></label>
								<input type="text" class="form-control" id="email">
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="subject"><%=t(".subject")%></label>
								<input type="text" class="form-control" id="subject">
							</div>
						</div>
						<div class="col-sm-12">
							<div class="form-group">
								<label for="message"><%=t(".message")%></label>
								<textarea id="message" class="form-control"></textarea>
							</div>
						</div>
						<div class="col-sm-12 text-center">
							<button type="submit" class="btn btn-template-main"><i class="fa fa-envelope-o"></i><%=t(".send")%></button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
<div>
		<div class="shop-button">
			<a href="<%= category_index_path %>"><i class="fa fa-briefcase fa-2x" aria-hidden="true"></i></a>
		</div>
		<div class="shop-button1">
			<a href="<%= new_user_session_path %>"><i class="fa fa-user fa-1x" aria-hidden="true"></i></a>
		</div>
		<!--<div class="shop-button2">
			<a href="<%= admin_index_path %>"><i class="fa fa-user-secret fa-1x" aria-hidden="true"></i></a>
		</div>-->

</div>

<!-- *** MAIL END *** -->