config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    #get  '/users' => 'home_page#home'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end





  root to: 'home_page#home'
  namespace :api, defaults:{ format: :json }do
      namespace :v1 do
        resources :products, :only => [:show,:index]
        resources :category_has_products, :only => [:show,:index]
      end
    end

  #  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  #devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope "(:locale)",locale:/#{I18n.available_locales.join("|")}/ do

  #  devise_scope :user do
  #      delete '/users/sign_out' => 'devise/sessions#destroy'
  #  end


    resources :category, except:[:delete] do
      collection do
        get 'show', to: :show
      end
      resources :product, only:[]  do
        collection do
          get 'showall', to: :showall
          get 'newest', to: :newest
          get 'pricelow', to: :pricelow
          get 'pricehigh', to: :pricehigh
        end
      end
      #resources :user do
      #  collection do
      #    get '/users/sign_out' => 'devise/sessions#destroy'
      #  end
      #end
    end

    resources :product, only:[]  do
      member do
        get 'show', to: :show
      end
    end

    resources :review, only: [] do
      collection do
        get 'create', to: :create
      end
    end

    scope 'admin' do
      resources :product do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          post 'change', to: :change
          get 'list', to: :list
          get 'status', to: :status
          get 'showimage', to: :showimage
          post 'sortimages', to: :sortimages
        end
      end
    end
    #assert_generates '../category/status', controller: 'category', action: 'status'
    scope 'admin' do
      resources :category do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          get 'list', to: :list
          get 'status', to: :status
          post 'change', to: :change
        end
      end
      resources :product_images do
         collection do
           post 'create', to: :create
           post 'createExisting', to: :createExisting
           post 'updateorder', to: :updateorder
         end
      end
    end

    post 'addtocart', to: 'application#addtocart'
    get 'addtocartget', to: 'application#addtocartget'
    get 'refreshcart', to: 'shop#refreshcart'


    resources :checkout, only: [] do
      collection do
        get 'index', to: :index
        get 'first', to: :first
        post 'first_data', to: :first
        get 'second', to: :second
        post 'second_data', to: :second_data
        get 'cart', to: :cart
        get 'deletecart', to: :deletecart
      end
    end

    resources :category, only: [] do
      resources :product, only: [] do
        collection do
          get 'showforcategory', to: :showforcategory
        end
      end
    end

    get 'home', to: 'home_page#home'
    get 'team', to: 'hometeam#index'
    get 'admin/index', to: 'admin#admin_index'

    resources :admin do
      collection do
        get 'userlist', to: :user
        get 'beadmin', to: :beadmin
        get 'removeadmin', to: :removeadmin
      end
    end
    resources :product_images
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

  respond_to :html, :js

  def index

    current_cart
    @productcart = []
    session[:cart].each do |key, array|
      e = Product.find( key.to_s )
      e.quantity = array
      @productcart << e
    end
    # respond_to do |format|
    #   format.html
    # end

  end

  def cart

    current_cart
    @productcart = []
    session[:cart].each do |key, array|
      e = Product.find( key.to_s )
      e.quantity = array
      @productcart << e
    end

    respond_to do |format|
      format.html
    end

  end
  def first

    respond_to do |format|
      format.js
    end

  end

  def first_data

    redirect_to second_checkout_index_path

  end

  def second

    respond_to do |format|
      format.js
    end

  end

  def second_data
  end

  def deletecart
    id = params[:id]
    current_cart
    @productcart = []
    session[:cart].delete( id )
    session[:cart].each do |key, array|
      e = Product.find( key.to_s )
      e.quantity = array
      @productcart << e
    end
    @productcart.each do |q|
      print q.name
    end
    respond_to do |format|
        format.js
    end
  end

  helper_method :total
  def total()
    @sum = 0.0
    session[:cart].each do |key, array|
      e = Product.find( key.to_s )
      e.quantity = array
      @productcart << e
    end
    @productcart.each do |p|
      if p.discount !=0.0
        @sum+=(p.price.to_i - p.discount.to_i)* p.quantity.to_i
      else
        @sum+= (p.price.to_i)*p.quantity.to_i
      end
    end
    return @sum/2
  end

end

app/views/checkout/_deletecart.html.erb
<div class="container">
   <div class="row">
       <div class="col-md-9 clearfix" id="checkout">
           <div class="box">
             <div class="content" id="tbContent">
                 <div class="table-responsive">
                     <table class="table" id= "tbCart">
                         <thead>
                             <tr>
                                 <th colspan="2">Product</th>
                                 <th> </th>
                                 <th>Quantity</th>
                                 <th>Unit price</th>
                                 <th>Discount</th>
                                 <th colspan="2">Total</th>
                                 <th><th>
                             </tr>
                         </thead>
                         <tbody>
                           <% @productcart.each do |i| %>
                             <tr>
                                 <td>
                                   <% showImage = ProductImage.find_by(product_id: i.id.to_s ) %>
                                   <% unless showImage.nil?%>
                                     <td><%=image_tag showImage.image.thumb.url%></td>
                                   <%else%>
                                     <td>No image</td>
                                   <%end%>
                                 </td>
                                 <td><a href="<%= product_path(i.id) %>"><%= i.name %></a>
                                 </td>
                                 <td> <select value="<%= i.quantity %>" id="squantity">
                                   <% for a in (1..Product.find( i.id ).quantity) %>
                                       <option value="<%=a%>"><%=a%></option>
                                   <% end %>
                                 </select></td>
                                 <td><%= i.price %></td>
                                 <td><%= i.discount %></td>
                                 <%if i.discount !=0.0%>
                                   <td>$<%= (i.price - i.discount) * i.quantity %></td>
                                 <%else%>
                                   <td>$<%= i.price * i.quantity %></td>
                                 <%end%>
                                 <td><%= link_to '', deletecart_checkout_index_path( :id => i.id ),:title =>"Delete item" ,:id=> "deleteItem", :class=>"btn fa fa-trash-o", remote: true %></td>
                             </tr>
                          <% end %>
                         </tbody>
                         <tfoot>
                             <tr>
                                 <th colspan="6">Total</th>
                                 <%@sum = total()%>
                                 <th>$<%= @sum%></th>
                             </tr>
                         </tfoot>
                     </table>
                 </div>
                 <!-- /.table-responsive -->
             </div>
             <!-- /.content -->
             <div class="box-footer">
                 <div class="pull-right">
                     <a href="<%= checkout_index_path %>" class="btn btn-template-main">Checkout<i class="fa fa-chevron-right"></i>
                     </a>
                 </div>
             </div>
           </div>
           <!-- /.box -->
       </div>
       <!-- /.col-md-9 -->
       <div class="col-md-3">
           <div class="box" id="order-summary">
               <div class="box-header">
                   <h3>Order summary</h3>
               </div>
               <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>
               <div class="table-responsive">
                   <table class="table">
                       <tbody>
                           <tr>
                               <td>Order subtotal</td>
                               <th>$<%= @sum%></th>
                           </tr>
                           <tr>
                               <td>Shipping and handling</td>
                               <th>$0.00</th>
                           </tr>
                           <tr>
                               <td>Tax</td>
                               <th>$0.00</th>
                           </tr>
                           <tr class="total">
                               <td>Total</td>
                               <th>$<%= @sum%></th>
                           </tr>
                       </tbody>
                   </table>
               </div>
           </div>
       </div>
       <!-- /.col-md-3 -->
   </div>
   <!-- /.row -->
</div>
 <!--/.container  -->

app/views/checkout/_first.html.erb
<div class="box">
  <ul class="nav nav-pills nav-justified">
      <li class="disabled"><a href="#"><i class="fa fa-eye"></i><br>Order Review</a>
      </li>
      <li class="active"><a href="#"><i class="fa fa-map-marker"></i><br>Address</a>
      </li>
      <li class="disabled"><a href="#"><i class="fa fa-money"></i><br>Payment Method</a>
      </li>

  </ul>

  <div class="content">
      <div class="row">
          <div class="col-sm-6">
              <div class="form-group">
                  <label for="firstname">Firstname</label>
                  <input type="text" class="form-control" id="firstname">
              </div>
          </div>
          <div class="col-sm-6">
              <div class="form-group">
                  <label for="lastname">Lastname</label>
                  <input type="text" class="form-control" id="lastname">
              </div>
          </div>
      </div>
      <!-- /.row -->

      <div class="row">
          <div class="col-sm-6">
              <div class="form-group">
                  <label for="company">Company</label>
                  <input type="text" class="form-control" id="company">
              </div>
          </div>
          <div class="col-sm-6">
              <div class="form-group">
                  <label for="street">Street</label>
                  <input type="text" class="form-control" id="street">
              </div>
          </div>
      </div>
      <!-- /.row -->

      <div class="row">
          <div class="col-sm-6 col-md-3">
              <div class="form-group">
                  <label for="city">City</label>
                  <input type="text" class="form-control" id="city">
              </div>
          </div>
          <div class="col-sm-6 col-md-3">
              <div class="form-group">
                  <label for="zip">ZIP</label>
                  <input type="text" class="form-control" id="zip">
              </div>
          </div>
          <div class="col-sm-6 col-md-3">
              <div class="form-group">
                  <label for="state">State</label>
                  <select class="form-control" id="state"></select>
              </div>
          </div>
          <div class="col-sm-6 col-md-3">
              <div class="form-group">
                  <label for="country">Country</label>
                  <select class="form-control" id="country"></select>
              </div>
          </div>

          <div class="col-sm-6">
              <div class="form-group">
                  <label for="phone">Telephone</label>
                  <input type="text" class="form-control" id="phone">
              </div>
          </div>
          <div class="col-sm-6">
              <div class="form-group">
                  <label for="email">Email</label>
                  <input type="text" class="form-control" id="email">
              </div>
          </div>

      </div>
      <!-- /.row -->
  </div>

  <div class="box-footer">
      <div class="pull-left">
          <a href="<%= checkout_index_path %>" class="btn btn-default"><i class="fa fa-chevron-left"></i>Order</a>
      </div>
      <div class="pull-right">
          <button type="submit" id="first" class="btn btn-template-main">Payment Method<i class="fa fa-chevron-right"></i>
          </button>
      </div>
  </div>

</div>
<!-- /.box -->

app/views/checkout/_second.html.erb
<div class="box">

        <ul class="nav nav-pills nav-justified">
            <li class="disabled"><a href="shop-checkout4.html"><i class="fa fa-eye"></i><br>Order Review</a>
            </li>
            <li class="disabled"><a><i class="fa fa-map-marker"></i><br>Address</a>
            </li>
            <li class="active"><a href="#"><i class="fa fa-money"></i><br>Payment Method</a>
            </li>
        </ul>
        <div class="content">
            <div class="row">
                <div class="col-sm-6">
                    <div class="box payment-method">

                        <h4><i class="fa fa-paypal" aria-hidden="true"></i>Paypal</h4>

                        <p>We like it all.</p>

                        <div class="box-footer text-center">
                            <div class="checkbox checkbox-primary">
                              <input type="checkbox" id="checkbox" name="payment" value="payment1">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="box payment-method">

                        <h4><i class="fa fa-credit-card" aria-hidden="true"></i>Payment gateway</h4>

                        <p>VISA and Mastercard only.</p>

                        <div class="box-footer text-center">
                          <div class="checkbox checkbox-primary">
                            <input type="checkbox" id="checkbox" name="payment" value="payment2">
                          </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /.row -->

        </div>
        <!-- /.content -->

        <div class="box-footer">
            <div class="pull-left">
                <button type="submit" id="index" class="btn btn-template-main"><i class="fa fa-chevron-left"></i>Address
                </button>
            </div>
            <div class="pull-right">
                <button type="submit" class="btn btn-template-main">Finish<i class="fa fa-chevron-right"></i>
                </button>
            </div>
        </div>

</div>
<!-- /.box -->

app/views/checkout/address.html.erb
<div id="heading-breadcrumbs">
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <h1>Checkout - Address</h1>
                    </div>
                    <div class="col-md-5">
                        <ul class="breadcrumb">
                            <li><a href="index.html">Home</a>
                            </li>
                            <li>Checkout - Address</li>
                        </ul>

                    </div>
                </div>
            </div>
        </div>

        <div id="content">
            <div class="container">

                <div class="row">

                    <div class="col-md-9 clearfix" id="checkout">

                        <div class="box">


                                <ul class="nav nav-pills nav-justified">
                                    <li class="active"><a href="#"><i class="fa fa-map-marker"></i><br>Address</a>
                                    </li>
                                    <li class="disabled"><a href="#"><i class="fa fa-money"></i><br>Payment Method</a>
                                    </li>
                                    <li class="disabled"><a href="#"><i class="fa fa-eye"></i><br>Order Review</a>
                                    </li>
                                </ul>

                                <div class="content">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="firstname">Firstname</label>
                                                <input type="text" class="form-control" id="firstname">
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="lastname">Lastname</label>
                                                <input type="text" class="form-control" id="lastname">
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.row -->

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="company">Company</label>
                                                <input type="text" class="form-control" id="company">
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="street">Street</label>
                                                <input type="text" class="form-control" id="street">
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.row -->

                                    <div class="row">
                                        <div class="col-sm-6 col-md-3">
                                            <div class="form-group">
                                                <label for="city">City</label>
                                                <input type="text" class="form-control" id="city">
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-3">
                                            <div class="form-group">
                                                <label for="zip">ZIP</label>
                                                <input type="text" class="form-control" id="zip">
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-3">
                                            <div class="form-group">
                                                <label for="state">State</label>
                                                <select class="form-control" id="state"></select>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-3">
                                            <div class="form-group">
                                                <label for="country">Country</label>
                                                <select class="form-control" id="country"></select>
                                            </div>
                                        </div>

                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="phone">Telephone</label>
                                                <input type="text" class="form-control" id="phone">
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="email">Email</label>
                                                <input type="text" class="form-control" id="email">
                                            </div>
                                        </div>

                                    </div>
                                    <!-- /.row -->
                                </div>

                                <div class="box-footer">
                                    <div class="pull-left">
                                        <a href="shop-basket.html" class="btn btn-default"><i class="fa fa-chevron-left"></i>Back to basket</a>
                                    </div>
                                    <div class="pull-right">
                                        <button type="submit" id="first" class="btn btn-template-main">Continue to Delivery Method<i class="fa fa-chevron-right"></i>
                                        </button>
                                    </div>
                                </div>

                        </div>
                        <!-- /.box -->


                    </div>
                    <!-- /.col-md-9 -->

                    <div class="col-md-3">

                        <div class="box" id="order-summary">
                            <div class="box-header">
                                <h3>Order summary</h3>
                            </div>
                            <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

                            <div class="table-responsive">
                                <table class="table">
                                    <tbody>
                                        <tr>
                                            <td>Order subtotal</td>
                                            <th>$446.00</th>
                                        </tr>
                                        <tr>
                                            <td>Shipping and handling</td>
                                            <th>$10.00</th>
                                        </tr>
                                        <tr>
                                            <td>Tax</td>
                                            <th>$0.00</th>
                                        </tr>
                                        <tr class="total">
                                            <td>Total</td>
                                            <th>$456.00</th>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                        </div>

                    </div>
                    <!-- /.col-md-3 -->

                </div>
                <!-- /.row -->

            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->

app/views/checkout/cart.html.erb
<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Cart</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb">
                    <li><a href="<%= root_path %>">Home</a>
                    </li>
                    <li>Cart</li>
                </ul>

            </div>
        </div>
    </div>
</div>

<div id="contentcart">
  <%= render 'checkout/deletecart'%>
</div>
  <!-- /#content -->

app/views/checkout/deletecart.js.erb
$( "#contentcart" ).html( "<%= escape_javascript( render( "deletecart" ) ) %>" );

app/views/checkout/first.js.erb
$( "#checkout" ).html( "<%= escape_javascript( render( "first" ) ) %>" );

app/views/checkout/index.html.erb
<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Checkout</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb">
                    <li><a href="<%= root_path %>">Home</a>
                    </li>
                    <li>Checkout</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="content">
  <div class="container">

     <div class="row">

         <div class="col-md-9 clearfix" id="checkout">

             <div class="box">

                     <ul class="nav nav-pills nav-justified">
                         <li class="active"><a href="#"><i class="fa fa-eye"></i><br>Order Review</a>
                         </li>
                         <li class="disabled"><a><i class="fa fa-map-marker"></i><br>Address</a>
                         </li>
                         <li class="disabled"><a><i class="fa fa-money"></i><br>Payment Method</a>
                         </li>
                     </ul>

                     <div class="content">
                         <div class="table-responsive">
                             <table class="table">
                                 <thead>
                                     <tr>
                                       <th colspan="2">Product</th>
                                       <th> </th>
                                       <th>Quantity</th>
                                       <th>Unit price</th>
                                       <th>Discount</th>
                                       <th colspan="2">Total</th>
                                     </tr>
                                 </thead>
                                 <tbody>
                                   <% @productcart.each do |i| %>
                                     <tr>
                                         <td>
                                           <% showImage = ProductImage.find_by(product_id: i.id.to_s ) %>
                                           <% unless showImage.nil?%>
                                             <td><%=image_tag showImage.image.thumb.url%></td>
                                           <%else%>
                                             <td>No image</td>
                                           <%end%>
                                         </td>
                                         <td><a href="<%= product_path(i.id) %>"><%= i.name %></a>
                                         </td>
                                         <td><%= i.quantity %></td>
                                         <td><%= i.price %></td>
                                         <td><%= i.discount %></td>
                                         <%if i.discount !=0.0%>
                                           <td>$<%= (i.price - i.discount) * i.quantity %></td>
                                         <%else%>
                                           <td>$<%= i.price * i.quantity %></td>
                                         <%end%>
                                     </tr>
                                  <% end %>
                                 </tbody>
                                 <tfoot>
                                     <tr>
                                         <th colspan="6">Total</th>
                                         <%@sum = total()%>
                                         <th>$<%= @sum %></th>
                                     </tr>
                                 </tfoot>
                             </table>

                         </div>
                         <!-- /.table-responsive -->
                     </div>
                     <!-- /.content -->

                     <div class="box-footer">
                         <div class="pull-left">
                             <a href="<%= cart_checkout_index_path %>" class="btn btn-default"><i class="fa fa-chevron-left"></i>Cart</a>
                         </div>
                         <div class="pull-right">
                             <button type="submit" id="index" class="btn btn-template-main">Address<i class="fa fa-chevron-right"></i>
                             </button>
                         </div>
                     </div>

             </div>
             <!-- /.box -->
         </div>
         <!-- /.col-md-9 -->

         <div class="col-md-3">

             <div class="box" id="order-summary">
                 <div class="box-header">
                     <h3>Order summary</h3>
                 </div>
                 <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

                 <div class="table-responsive">
                     <table class="table">
                         <tbody>
                             <tr>
                                 <td>Order subtotal</td>
                                 <th><%= @sum%></th>
                             </tr>
                             <tr>
                                 <td>Shipping and handling</td>
                                 <th>$0.00</th>
                             </tr>
                             <tr>
                                 <td>Tax</td>
                                 <th>$0.00</th>
                             </tr>
                             <tr class="total">
                                 <td>Total</td>
                                 <th>$<%= @sum%></th>
                             </tr>
                         </tbody>
                     </table>
                 </div>

             </div>

         </div>
         <!-- /.col-md-3 -->

     </div>
     <!-- /.row -->

 </div>

</div>
        <!-- /#content -->

app/views/checkout/second.js.erb
$( "#checkout" ).html( "<%= escape_javascript( render( "second" ) ) %>" );