config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    #get  '/users' => 'home_page#home'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end





  root to: 'home_page#home'
  namespace :api, defaults:{ format: :json }do
      namespace :v1 do
        resources :products, :only => [:show,:index]
        resources :category_has_products, :only => [:show,:index]
      end
    end

  #  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  #devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope "(:locale)",locale:/#{I18n.available_locales.join("|")}/ do

  #  devise_scope :user do
  #      delete '/users/sign_out' => 'devise/sessions#destroy'
  #  end


    resources :category, except:[:delete] do
      collection do
        get 'show', to: :show
      end
      resources :product, only:[]  do
        collection do
          get 'showall', to: :showall
          get 'newest', to: :newest
          get 'pricelow', to: :pricelow
          get 'pricehigh', to: :pricehigh
        end
      end
      #resources :user do
      #  collection do
      #    get '/users/sign_out' => 'devise/sessions#destroy'
      #  end
      #end
    end

    resources :product, only:[]  do
      member do
        get 'show', to: :show
      end
    end

    resources :review, only: [] do
      collection do
        get 'create', to: :create
      end
    end

    scope 'admin' do
      resources :product do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          post 'change', to: :change
          get 'list', to: :list
          get 'status', to: :status
          get 'showimage', to: :showimage
          post 'sortimages', to: :sortimages
        end
      end
    end
    #assert_generates '../category/status', controller: 'category', action: 'status'
    scope 'admin' do
      resources :category do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          get 'list', to: :list
          get 'status', to: :status
          post 'change', to: :change
        end
      end
      resources :product_images do
         collection do
           post 'create', to: :create
           post 'createExisting', to: :createExisting
           post 'updateorder', to: :updateorder
         end
      end
    end

    post 'addtocart', to: 'application#addtocart'
    get 'addtocartget', to: 'application#addtocartget'
    get 'refreshcart', to: 'shop#refreshcart'


    resources :checkout, only: [] do
      collection do
        get 'index', to: :index
        get 'first', to: :first
        post 'first_data', to: :first
        get 'second', to: :second
        post 'second_data', to: :second_data
        get 'cart', to: :cart
        get 'deletecart', to: :deletecart
      end
    end

    resources :category, only: [] do
      resources :product, only: [] do
        collection do
          get 'showforcategory', to: :showforcategory
        end
      end
    end

    get 'home', to: 'home_page#home'
    get 'team', to: 'hometeam#index'
    get 'admin/index', to: 'admin#admin_index'

    resources :admin do
      collection do
        get 'userlist', to: :user
        get 'beadmin', to: :beadmin
        get 'removeadmin', to: :removeadmin
      end
    end
    resources :product_images
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  belongs_to :country
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  has_many :line_product
  has_one :order
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product, through: :categoryHasProduct
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :address
  has_many :order
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :couponUse
end

app/models/coupon_use.rb
class CouponUse < ApplicationRecord
  belongs_to :customer
  has_one :coupon
  has_one :order
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :order
  has_many :cart
  has_many :couponUse
  has_many :address
  has_many :customerTransaction
  has_one :user
end

app/models/line_product.rb
class LineProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :OrderStatus
  belongs_to :country
  belongs_to :customer
  belongs_to :cart
  belongs_to :confirmation_order
  has_one :return
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :categories, through: :categoryHasProduct
  has_many :product_images
  has_many :reviews
  has_one :return
end

app/models/product_discount.rb
class ProductDiscount < ApplicationRecord
  belongs_to :product
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ImageUploader
  validates_processing_of :image
  validate :image_size_validation

  
  private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end

end

app/models/return.rb
class Return < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #before_action :authenticate_user!
#  before_create :generate_authentication_token!
  #before_filter :authenticate_user!
  has_many :review
  belongs_to :customer, optional: true



  def self.find_for_facebook_oauth(auth)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    # The User was found in our database
    return user if user
    # Check if the User is already registered without Facebook
    user = User.where(email: auth.info.email).first
    return user if user
    user = User.new(
         name: auth.extra.raw_info.name,
         provider: auth.provider, uid: auth.uid,
         email: auth.info.email,
         password: Devise.friendly_token[0,20])
    user.skip_confirmation!
    user.save
    user
   end

#=end
#  def self.create_with_omniauth(auth)
  #  create! do |user|
#      user.provider = auth["provider"]
#      user.uid = auth["uid"]
#      user.name = auth["info"]["name"]
#    end
#  end


#  private
  #  def generate_authentication_token!#
  #      begin
  #      self.auth_token = Devise.friendly_token
    #  end while self.class.exists?(auth_token: auth_token)
  #  end


    def admin?
      self.role == 53
    end

    def linguist?
      self.role == 7
    end


end

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_error_messages!
    flash_alerts = []
    error_key = 'errors.messages.not_saved'

    if !flash.empty?
      flash_alerts.push(flash[:error]) if flash[:error]
      flash_alerts.push(flash[:alert]) if flash[:alert]
      flash_alerts.push(flash[:notice]) if flash[:notice]
      error_key = 'devise.failure.invalid'
    end

    return "" if resource.errors.empty? && flash_alerts.empty?
    errors = resource.errors.empty? ? flash_alerts : resource.errors.full_messages

    messages = errors.map { |msg| content_tag(:li, msg) }.join
    #sentence = I18n.t(error_key, :count    => errors.count,
    #                             :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="messages" id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

app/helpers/hometeam_helper.rb
module HometeamHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/_userlist.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Users</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Users</h3>
      </div>
      <div class="panel-body">
        <div class="tab-pane" id="tab-discount">
          <div class="table-responsive">
            <table id="discount" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <td class="text-left">Id</td>
                  <td class="text-left">Email</td>
                  <td class="text-left">Role</td>
                  <td class="text-left">Status</td>
                  <td class="text-left">Action</td>
                </tr>
              </thead>
              <tbody>
                <% @userslist.each do |t| %>
                <tr>
                  <td><%= t.id %></td>
                  <td><%= t.email %></td>
                  <td><%= t.role %></td>

                  <td> Active </td>
                  <td><!-- <a href="/category/edit/<%= t.id %>" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>-->
                  <%= link_to '', beadmin_admin_index_path( :id => t.id ), :class=>"btn btn-default fa fa-arrow-circle-up", remote: true %>
                  <%= link_to '', removeadmin_admin_index_path( :id => t.id ), :class=>"btn btn-default fa fa-arrow-circle-down", remote: true %>
                  <!--<%= link_to '', status_category_index_path( :id => t.id ), :class=>"btn btn-default fa fa-eye", remote: true %>-->
                  <!-- <a href="/category/status/<%= t.id %>" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></td>
                  <a href="/admin/index" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></div></td> -->
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/admin/admin/admin_index.html.erb
<div id="indexcambio">

  <%= render 'admin/index' %>

</div>

app/views/admin/admin/userlist.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "userlist" ) ) %>" );

app/views/admin/admin_index.html.erb
<div id="indexcambio">

  <%= render 'admin/index' %>

</div>

app/views/admin/userlist.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "userlist" ) ) %>" );

app/views/layouts/OLD_copy.html.erb
<div class="copy-section">
	<div class="container">
		<div class="copy-left">
			<p>&copy; 2016 New Shop . All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
		</div>
		<div class="copy-right">
			<%= image_tag("vendor/card.png") %>
		</div>
		<div class="clearfix"></div>
	</div>
</div>

app/views/layouts/OLD_footer.html.erb
<div class="footer">
	<div class="footer-container">
		<div class="footer-col">
			<%= image_tag("shop/location-footer.png") %>
			<p>
				U.S.A. Office<br>
				1312 Elm Dr.<br>
				Office 1<br>
				Wylie, Texas<br>
				United States of America<br>
				Colombia Office<br>
				Carrera 60#4g-59<br>
				Bogota, Colombia<br>
				Coming Soon<br>
				Riohacha, Colombia
			</p>
		</div>
		<div class="footer-col">
			<%= image_tag("shop/mail-footer.png") %>
			<p>
				e-Mail us<br>
				Help@Wayuu-Mochila-Bags.com
			</p>
		</div>
		<div class="footer-col">
			<%= image_tag("shop/phone-footer.png") %>
			<p>
				Toll Free 1(855) WAYUU-55<br>
				or <br>
				1(855) 929-8855
			</p>
		</div>
	</div>
</div>
<div class="copyright">Copyright 2016<br>Wayuu Developer Team</div>

app/views/layouts/_adminNav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0px; background-color: #222222;">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html" style="color: white; font-size: 1.5em; font-family: georgia; margin-top: 6px">Administrator</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class=" glyphicon glyphicon-home" style="font-size: 24px;color: white">
            </a>
            <ul class="dropdown-menu dropdown-messages">
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>Read All Messages</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-messages -->
        </li>

            <!-- /.dropdown-tasks -->

            <!-- /.dropdown-alerts -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <span class=" glyphicon glyphicon-user" style="font-size: 24px;color: white">
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation" style="margin-top:70px">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="/admin/index"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-usd fa-fw"></i>Sales<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="flot.html">Latest sales</a>
                        </li>
                        <li>
                            <a href="morris.html">Show all</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-archive fa-fw"></i>Products<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <%= link_to 'Show all', list_product_index_path, remote: true %>
                        </li>

                        <li>
                            <!-- <a href="/admin/product/add">Add product</a> -->
                          <%= link_to 'New product', add_product_index_path( :format=>'js' ), remote: true %>
                        </li>
                        <li>

                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-users fa-fw"></i>Categories<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <%= link_to 'Show all', list_category_index_path, remote: true %>
                        </li>
                        <li>
                            <%= link_to 'New category', add_category_index_path( :format=>'js' ), remote: true %>
                        </li>


                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-users fa-fw"></i>Users<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>

                            <%= link_to 'Show all', userlist_admin_index_path, remote: true %>
                        </li>
                        <li>
                            <a href="morris.html">Morris.js Charts</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

app/views/layouts/_header.html.erb
<header>
	<!-- *** TOP *** -->
	<div id="top">
		<div class="container">
			<div class="row">
				<div class="col-xs-2 col-sm-1 col-md-2 dropdown top-left">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
						<p><i class="fa fa-globe" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Language</span></p>
					</a>
					<ul class="dropdown-menu">
						<li><%=link_to "English ",locale: "en"%></li>
						<li><%=link_to "Español ",locale: "es"%></li>
					</ul>
				</div>
				<p class="col-xs-6 col-sm-3 col-md-2 top-left">
					<i class="fa fa-phone"></i> 1(855) 929-8855
				</p>
				<div class="hidden-xs col-sm-3 col-md-3 social">
					<a href="https://www.facebook.com/WayuumBags" class="external facebook"><i class="fa fa-facebook"></i></a>
					<a href="https://plus.google.com/+WayuumochilabagsStore" class="external gplus"><i class="fa fa-google-plus"></i></a>
					<a href="https://www.instagram.com/wayuumbags" class="external instagram"><i class="fa fa-instagram"></i></a>
					<a href="https://twitter.com/wayuumbags" class="external twitter"><i class="fa fa-twitter"></i></a>
					<a href="http://wayuumbags.tumblr.com/" class="external tumblr hidden-sm"><i class="fa fa-tumblr"></i></a>
					<a href="https://www.youtube.com/channel/UCL30I8UIIDth2U-KHJm2Fpw" class="external youtube hidden-sm"><i class="fa fa-youtube"></i></a>
				</div>
				<div class="col-xs-4 col-sm-5 col-md-5">
					<div class="login">
						<% if not current_user %>
							<a href="#" data-toggle="modal" data-target="#myModal4"><i class="fa fa-sign-in"></i> <span class="hidden-xs text-uppercase"><%=t('.log_in')%></span></a>
							<a href="<%= new_user_registration_path %>"><i class="fa fa-user-plus"></i><span class="hidden-xs text-uppercase"><%=t('.sign_up')%></span></a>
						<% else %>
						    <%= link_to "Sign Out", destroy_user_session_path, class: "fa fa-sign-out", id: "hidden-xs", :method => 'delete' %>
								<!--<i class="fa fa-sign-out"></i><span class="hidden-xs text-uppercase"><%=t('.sign_out')%></span></a>-->
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- *** TOP END *** -->
	<!-- *** NAVBAR *** -->
	<div class="navbar-affixed-top" data-spy="affix" data-offset-top="200">
		<div class="navbar navbar-default yamm" role="navigation" id="navbar">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand home" href="/home">
						<%= image_tag("shop/logo.png", class: "hidden-xs hidden-sm logo-header") %>
						<%= image_tag("shop/logo.png", class: "visible-xs visible-sm logo-small-header") %><span class="sr-only">Wayuu - go to homepage</span>
					</a>
					<div class="navbar-buttons">
						<button type="button" class="navbar-toggle btn-template-main" data-toggle="collapse" data-target="#navigation">
							<span class="sr-only">Toggle navigation</span>
							<i class="fa fa-align-justify"></i>
						</button>
					</div>
					<div id="cart-container" class="hidden-sm hidden-md hidden-lg">
						<a id="navbar-cart" href="<%= cart_checkout_index_path %>"><i class="fa fa-shopping-cart"></i><span class="cart-count">0</span></a>
					</div>
				</div>
				<div class="navbar-collapse collapse" id="navigation">
					<ul class="nav navbar-nav navbar-right">
						<li class="active">
							<%= link_to("Home ", "/home")%>
						</li>
						<li> </li>
						<li class="dropdown">
							<a href="javascript: void(0)" class="dropdown-toggle" data-toggle="dropdown"><%=t(".shop")%><b class="caret"></b></a>
							<ul class="dropdown-menu">
								<%allCategories = Category.all.order("name ASC")%>
								<li><a href="/category/show">All Categories</a></li>
								<li><a href="#">Flash Sale</a></li>
								<li><a href="#">Gift Cards</a></li>
								<%allCategories.each do |c|%>
								<li><a href="<%= showall_category_product_index_path(c.id.to_s) %>"><%=c.name%></a></li>
								<%end%>
							</ul>
						</li>
						<li>
							<a href="javascript: void(0)">Blog </a>
						</li>
						<li class="dropdown">
							<a href="javascript: void(0)" class="dropdown-toggle" data-toggle="dropdown"><%=t('.about_us')%><b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#"><%=t('.survey')%></a></li>
								<li><a href="#"><%=t('.reviews')%></a></li>
								<li><a href="#">FAQ's</a></li>
								<li><a href="#"><%=t('.shipping')%></a></li>
								<li><a href="#"><%=t('.return')%></a></li>
								<li><a href="#"><%=t('.privacy')%></a></li>
								<li><a href="#"><%=t('.terms')%></a></li>
								<li><%= link_to(t('.team'), "team")%></li>
							</ul>
						</li>
						<li class="hidden-xs">
							<a id="navbar-cart" class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-shopping-cart"></i><span class="cart-count"><div id="number"><%= session[:cart].count %></div></span></a>
							<ul class="dropdown-menu" id="refresh">

								<li class="pull-right"><button id="refresh" class="btn btn-template-main"><i class="fa fa-refresh fa-lg"></i>Update</button></button></li>
								<br><br>

								<li>
									<a class="text-center" href="<%= cart_checkout_index_path %>">
										<button href="<%= cart_checkout_index_path %>" class="btn btn-template-main" disabled><i class="fa fa-shopping-cart"></i>Go to cart</button>
									</a>
								</li>

							</ul>
						</li>
						<li>
							<div class="social hidden-sm hidden-md hidden-lg">
								<a href="https://www.facebook.com/WayuumBags" class="external facebook"><i class="fa fa-facebook"></i></a>
								<a href="https://plus.google.com/+WayuumochilabagsStore" class="external gplus"><i class="fa fa-google-plus"></i></a>
								<a href="https://www.instagram.com/wayuumbags" class="external instagram"><i class="fa fa-instagram"></i></a>
								<a href="https://twitter.com/wayuumbags" class="external twitter"><i class="fa fa-twitter"></i></a>
								<a href="http://wayuumbags.tumblr.com/" class="external tumblr"><i class="fa fa-tumblr"></i></a>
								<a href="https://www.youtube.com/channel/UCL30I8UIIDth2U-KHJm2Fpw" class="external youtube"><i class="fa fa-youtube"></i></a>
							</div>
						</li>
					</ul>
				</div>
				<div class="collapse clearfix" id="search">
					<form class="navbar-form" role="search">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Search">
							<span class="input-group-btn">
								<button type="submit" class="btn btn-template-main"><i class="fa fa-search"></i></button>
							</span>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- *** NAVBAR END *** -->
</header>
<!-- *** LOGIN MODAL *** -->
<div class="modal fade" id="myModal4" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div align="center">
				<div class="card card-container1" align="center">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<div class="modal-title1" style="font-size:38px " align="center">
							Log in
						</div>
					</div>
				</br>
					<% if controller_name != 'confirmations' or controller_name != 'passwords' or controller_name != 'unlocks' %>
					<div align="center">
					<div class="row" align="center">
					    <div class="cuadro3" align="center">
					      <!--<i class="fa fa-facebook-official" aria-hidden="true" align="center" style="color:white"></i>-->
					      <%= link_to "Facebook", omniauth_authorize_path(resource_name, :facebook), :class=>"button"%>
					    </div>
					    <div class="cuadro4"  align="center">
					      <i class="fa fa-google-plus" style="color:white" ></i>
					      Google
					    </div>
					  </div>
					</div>
					<% end %>
					<div class="modal-body">
						<!--<img id="profile_img2" class="profile-img2-card" src="<%= asset_path("profileimg.jpg") %>">-->
						<div class="form-signin">
							<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>

							<% f.label :email %>
							<%= f.email_field :email, :id=>"inputEmail", :class=>"form-control", :placeholder=>"Email", autofocus: true, autocomplete: "off" %>

							<% f.label :password %>
							<%= f.password_field :password, :id=>"inputPassword", :class=>"form-control", :placeholder=>"Password", :align=>"center", autofocus: true, autocomplete: "off" %>

							<div class="fonts">
								<% if devise_mapping.rememberable? %>
								<%= f.check_box :remember_me %>
								<%= f.label :remember_me, :id=>"remember_me", autofocus: true, autocomplete: "off" %>
								<% end %>
							</div>
							<div class="row">
								<div align="center">
									<div class="form-group">
										<button class="btn btn-signin"></i> Log in</button>
										<!--<button align="center" class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>-->
										<% f.submit "Log in" %>
									</div>
								</div>
							</div>
						</div>
						<p class="text-center text-muted">Not registered yet? <a href="<%= new_user_registration_path %>"><strong>Register now</strong></a>! It is easy and done in 1&nbsp;minute and gives you access to special discounts and much more!</p>
						<div class="fontlinks">
							<%= render "devise/shared/links" %>
						</div>
						<% end %>
					</div>
					<!--<p class="text-center">
						<button class="btn btn-template-main"><i class="fa fa-sign-in"></i> Log in</button>
					</p>
					<div id="login-social">
						<a id="login-facebook"><i class="fa fa-facebook"></i></a>
						<a id="login-google"><i class="fa fa-google"></i></a>
					</div>-->
				</div>
			</div>
		</div>
	</div>
</div>

<!-- *** LOGIN MODAL END *** -->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Administrator</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'admin', media: 'all' %>
  </head>
  <body>
    <div id="wrapper">
    <%= render 'layouts/adminNav' %>
    <%= yield %>
    </div>
  </body>
</html>
<%= javascript_include_tag 'admin' %>