config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    #get  '/users' => 'home_page#home'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end





  root to: 'home_page#home'
  namespace :api, defaults:{ format: :json }do
      namespace :v1 do
        resources :products, :only => [:show,:index]
        resources :category_has_products, :only => [:show,:index]
      end
    end

  #  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  #devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope "(:locale)",locale:/#{I18n.available_locales.join("|")}/ do

  #  devise_scope :user do
  #      delete '/users/sign_out' => 'devise/sessions#destroy'
  #  end


    resources :category, except:[:delete] do
      collection do
        get 'show', to: :show
      end
      resources :product, only:[]  do
        collection do
          get 'showall', to: :showall
          get 'newest', to: :newest
          get 'pricelow', to: :pricelow
          get 'pricehigh', to: :pricehigh
        end
      end
      #resources :user do
      #  collection do
      #    get '/users/sign_out' => 'devise/sessions#destroy'
      #  end
      #end
    end

    resources :product, only:[]  do
      member do
        get 'show', to: :show
      end
    end

    resources :review, only: [] do
      collection do
        get 'create', to: :create
      end
    end

    scope 'admin' do
      resources :product do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          post 'change', to: :change
          get 'list', to: :list
          get 'status', to: :status
          get 'showimage', to: :showimage
          post 'sortimages', to: :sortimages
        end
      end
    end
    #assert_generates '../category/status', controller: 'category', action: 'status'
    scope 'admin' do
      resources :category do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          get 'list', to: :list
          get 'status', to: :status
          post 'change', to: :change
        end
      end
      resources :product_images do
         collection do
           post 'create', to: :create
           post 'createExisting', to: :createExisting
           post 'updateorder', to: :updateorder
         end
      end
    end

    post 'addtocart', to: 'application#addtocart'
    get 'addtocartget', to: 'application#addtocartget'
    get 'refreshcart', to: 'shop#refreshcart'


    resources :checkout, only: [] do
      collection do
        get 'index', to: :index
        get 'first', to: :first
        post 'first_data', to: :first
        get 'second', to: :second
        post 'second_data', to: :second_data
        get 'cart', to: :cart
        get 'deletecart', to: :deletecart
      end
    end

    resources :category, only: [] do
      resources :product, only: [] do
        collection do
          get 'showforcategory', to: :showforcategory
        end
      end
    end

    get 'home', to: 'home_page#home'
    get 'team', to: 'hometeam#index'
    get 'admin/index', to: 'admin#admin_index'

    resources :admin do
      collection do
        get 'userlist', to: :user
        get 'beadmin', to: :beadmin
        get 'removeadmin', to: :removeadmin
      end
    end
    resources :product_images
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :categories, through: :categoryHasProduct
  has_many :product_images
  has_many :reviews
  has_one :return
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  respond_to :json
  def index
    @products = Product.all.order("id ASC")
    respond_with @products
  end
  def show
    respond_with Product.find(params[:id])
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

	respond_to :html, :js

	def index
		@id = Category.find( params[:id] )
		@products = Product.where("category_id = " + @id.id )
	end

	def add
		@cate = Category.all.order('name ASC')
  #render layout: "admin"
  respond_to do |format|
  	format.js
  end
end

def showall
	@count_products = CategoryHasProduct.where(:category_id => params[:category_id])
	@from_category = Category.find(params[:category_id])
	@show_products =[]
	@count_products.each do |p|
		@show_products.push(Product.find(p.product_id.to_s))
	end
	@show_products = @show_products.paginate(:page => params[:page],:per_page => 6)
end

def newest
	@newest = Product.joins("INNER JOIN category_has_products ON category_has_products.product_id = products.id WHERE category_id ="+ params[:category_id].to_s).order(created_at: :desc)
	@newest = @newest.paginate(:page => params[:page],:per_page => 6)
end

def pricelow
	@pricelow = Product.joins("INNER JOIN category_has_products ON category_has_products.product_id = products.id WHERE category_id ="+ params[:category_id].to_s).order(price: :asc)
	@pricelow = @pricelow.paginate(:page => params[:page],:per_page => 6)
end

def pricehigh
	@pricehigh = Product.joins("INNER JOIN category_has_products ON category_has_products.product_id = products.id WHERE category_id ="+ params[:category_id].to_s).order(price: :desc)
	@pricehigh = @pricehigh.paginate(:page => params[:page],:per_page => 6)
end

def new
	name = params['name']
	description = params['description']
	model = params['model']
	price = params['price']
	tax_class_id = params['tax_class_id']
	quantity = params['quantity']
	length = params['length']
	width = params['width']
	height = params['height']
	weight = params['weight']
	discount = params['product_discount_price']
	status = params['status']
	category1 = params['category1']
	@cat = Category.find_by name: category1.to_s
	product_discount_start = params['product_discount_start']
	product_discount_end = params['product_discount_end']
	if discount == ""
		discount = 0.0
	end

	temp = Product.new
	temp.name = name
	temp.quantity = quantity.to_i
	temp.description = description
	temp.price = price
	temp.length = length
	temp.width = width
	temp.height = height
	temp.status = status
	temp.discount = discount
	temp.weight = weight

	temp.save!
    #puts @stock.errors.any?
    #puts temp.errors.full_messages

    @catego = CategoryHasProduct.new
    @catego.product_id = temp.id
    @catego.category_id = @cat.id
    @catego.save!
    session[:productid] = temp.id
		session[:order] = 1
    #redirect_to list_product_index_path
    #@imagen = params['images']
    if request.xhr?
    	respond_to do |format|
    		format.js
    	end

    end


end

def show
#@list = Product.all.order("id ASC")
#@consult = CategoryHasProduct.all
#respond_to do |format|
#  format.js
#end
@product = Product.find( params[:id] )
@cate = Category.all.order('name ASC')
@comments = Review.where(product_id: params[:id]).order('created_at DESC')

respond_to do |format|
	format.html
end
render layout: "application"

puts @product
end


def edit
	@pro = Product.find( params[:id] )
	@cate = Category.all
	@sele = (CategoryHasProduct.find_by( product_id: @pro.id.to_s )).category_id
	@image_show = ProductImage.where( :product_id => @pro.id.to_s).order("sort_order")
end

def change
	t = Product.find( params[:id] )
	t.name = params['name']
	t.description = params['description']
	t.price = params['price']
	t.quantity = params['quantity']
	t.length = params['length']
	t.width = params['width']
	t.height = params['height']
	category1 = params['category1']
	discount = params['product_discount_price']
	if discount == ""
		discount = 0
	end
	t.discount = discount
	val = CategoryHasProduct.find_by( product_id: t.id )
	cat = Category.find_by( name: category1.to_s )

	val.category_id = cat.id

	val.save!
	t.save!
  #redirect_to list_product_index_path
end

def list
	@products = Product.all
end

def status
	@pro = Product.find( params[:id] )
	if @pro.status == "1"
		@pro.status = "0"
	else
		@pro.status = "1"
	end
	@pro.save!
	redirect_to list_product_index_path

end

def orderimages
	respond_to do |format|
		format.js
	end
end

def showforcategory

end

def sortimages
	arreglo = params['info']
  #puts arreglo.length
  #puts arreglo
  #puts "veaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  redirect_to list_product_index_path
end

end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/_addproduct.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <button data-toggle="tooltip" title="Save" id="addproduct" class="btn btn-primary"><i class="fa fa-save"></i></button>
      <button title="Saveimage" id="saveimage" class="btn btn-primary hidden"><i class="fa fa-save"></i></button>
      <a href="/admin/index" id="finishadd" title="Finish" class="btn btn-primary hidden"><i class="fa fa-check"></i></a>
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Product</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Add Product</h3>
      </div>
      <div class="panel-body" style="margin-top: 20px">
        <form action="/product/new" method="post" enctype="multipart/form-data" id="form-product" class="form-horizontal">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <ul class="nav nav-tabs">
            <li class="active" id="general"><a href="#tab-data" data-toggle="tab">General</a></li>
            <li id="link"><a href="#tab-links" data-toggle="tab">Categories</a></li>
            <li id="idImage" class="hidden"><a href="#tab-image" data-toggle="tab">Images</a></li>
          </ul>

          <div class="tab-content" style="margin-top: 15px">
            <div class="tab-pane active" id="tab-data">
              <div class="form-group required">
                <label class="col-sm-2 control-label" for="input-name">Name</label>
                <div class="col-sm-10">
                  <input type="text" name="product_name" value="" placeholder="Product name" id="name" class="form-control" />
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-description1">Description</label>
                <div class="col-sm-10">
                  <textarea name="product_description" placeholder="Description" style="min-width: 100%" id="description"></textarea>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-price">Price</label>
                <div class="col-sm-10">
                  <input type="text" name="price" value="" placeholder="Price" id="price" class="form-control" />
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-price">Discount</label>
                <div class="col-sm-10">
                  <input type="text" name="price" value="" placeholder="Discount" id="discount" class="form-control" />
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-tax-class">Tax Class</label>
                <div class="col-sm-10">
                  <select name="tax_class_id" id="tax_class_id" class="form-control">
                    <option value="0"> --- None --- </option>
                    <option value="9">Taxable Goods</option>
                  </select>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-quantity">Quantity</label>
                <div class="col-sm-10">
                  <input type="text" name="quantity" value="1" placeholder="Quantity" id="quantity" class="form-control" />
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-quantity">Weight</label>
                <div class="col-sm-10">
                  <input type="text" name="Weight" value="" placeholder="Weight" id="weight" class="form-control" />
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-length">Dimensions</label>
                <div class="col-sm-10">
                  <div class="row">
                    <div class="col-sm-4">
                      <input type="text" name="length" value="" placeholder="Length" id="length" class="form-control" />
                    </div>
                    <div class="col-sm-4">
                      <input type="text" name="width" value="" placeholder="Width" id="width" class="form-control" />
                    </div>
                    <div class="col-sm-4">
                      <input type="text" name="height" value="" placeholder="Height" id="height" class="form-control" />
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-status">Status</label>
                <div class="col-sm-10">
                  <select name="status" id="status" class="form-control">
                    <option value="1" selected="selected">Enabled</option>
                    <option value="0">Disabled</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="tab-pane" id="tab-links">
              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-category"><span data-toggle="tooltip" title="(Autocomplete)">Categories</span></label>
                <div class="col-sm-8">
                  <!--<input type="text" name="category1" value="" placeholder="Category" id="input-category" class="form-control" /><br>-->
                  <select class="form-control" data-live-search="true" id="category1" name="category1" style="font-size: 15px">
                    <%= @cate.each do |t| %>
                      <option style="font-size: 15px"><%= t.name %></option>
                    <% end %>
                  </select>
                </div>
              </div>
            </div>
            </form>
            <div class="tab-pane" id="tab-image">
              <div class="modal-body">
                <form method="post" action="/admin/product_images/create" id="image" class="dropzone" enctype="multipart/form-data">
                  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                  <div class="fallback">
                    <input name="media" type="file"/>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
    </div>

app/views/product/_listproduct.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Products</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Products</h3>
      </div>
      <div class="panel-body">
        <div class="tab-pane" id="tab-discount">
          <div class="table-responsive">
            <table id="discount" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <td class="text-left">Image</td>
                  <td class="text-left">Name</td>
                  <td class="text-left">Description</td>
                  <td class="text-left">Price</td>
                  <td class="text-left">Discount</td>
                  <td class="text-left">Category</td>
                  <td class="text-left">Discount</td>
                  <td class="text-left">Status</td>
                  <td class="text-left">Action</td>
                </tr>
              </thead>
              <tbody>
                <% @products.each do |t| %>
                <tr>
                  <% showImage = ProductImage.find_by(product_id: t.id.to_s ) %>
                  <% unless showImage.nil?%>
                    <td><%=image_tag showImage.image.thumb.url%></td>
                  <%else%>
                    <td>No image available</td>
                  <%end%>
                  <td><%= t.name %></td>
                  <td><%= t.description %></td>
                  <td><%= t.price %></td>
                  <td><%= t.discount %></td>
                  <td><%= Category.find( (((CategoryHasProduct.find_by( product_id: t.id.to_s  )).category_id).to_s) ).name %></td>
                  <td><%=ProductDiscount.where("product_id = " + t.id.to_s ).size %></td>
                  <% if t.status == "1" %>
                    <td>Active</td>
                  <% else %>
                    <td>Idle</td>
                  <% end %>
                  <td><!-- <a href="/category/edit/<%= t.id %>" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>-->
                  <%= link_to '', edit_product_path( :id => t.id ), :class=>"btn btn-default fa fa-pencil", remote: true %>

                  <%= link_to '', status_product_index_path( :id => t.id ), :class=>"btn btn-default fa fa-eye", remote: true %>
                  <!-- <a href="/category/status/<%= t.id %>" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></td>
                  <a href="/admin/index" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></div></td> -->
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/product/_newest.html.erb
<div id="addedsuccess"></div>
<div class="row products">
	<% @newest.each do |c| %>
	<div class="col-md-4 col-sm-6">
		<div class="product">
			<div>
				<div class="box-image custom-box-image">
					<div class="image" id= "pimage">
						<a href="<%=product_path( c.id ) %>">
							<%product_image = ProductImage.find_by(product_id: c.id.to_s )%>
							<%if product_image.nil?%>
							<!--img src="http://c9a023018b7727eeeae9-5cb13b2b77b05284d2f5230b4c21c288.r0.cf1.rackcdn.com/uploads/nopreview.png" alt="" class="img-responsive image1"-->
							<%= image_tag("shop/no-preview.jpg", class: "img-responsive image1") %>
							<%else%>
							<img src="<%=product_image.image.url%>" class="img-responsive">
							<%end%>
						</a>
					</div>
					<div class="text custom-text-add-to-cart">
						<a href="<%= addtocartget_path( :id => c.id ) %>" data-remote="true" class="btn btn-template-main" id="addedtocartbutton"><i class="fa fa-shopping-cart"></i>Add to cart</a>
					</div>
				</div>
				<% if c.discount != 0.0%>
				<div class="ribbon sale">
					<div class="theribbon">SALE</div>
					<div class="ribbon-background"></div>
				</div>
				<%end%>
				<% if c.created_at > 10.days.ago %>
				<div class="ribbon new">
					<div class="theribbon">NEW</div>
					<div class="ribbon-background"></div>
				</div>
				<% end %>
			</div>
			<div class="text">
				<h3><%=c.name%></h3>
				<% if c.discount != 0.0%>
				<p class="price">$<%= (c.price - c.discount)%><br><del>$<%= c.price%></del></p>
				<%else%>
				<p class="price">$<%=c.price%></p>
				<%end%>
              <!-- <p style="margin-top:15px;">
                <a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
            </p> -->
        </div>
    </div>
</div>
<%end%>
</div>
<div class="col-sm-12">
	<div class="center">
		<%= will_paginate @newest, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 1,previous_label: "«" , next_label: "»"%>
	</div>
</div>

app/views/product/_order.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

   <div class="container-fluid">

    <div class="pull-right">
      <button type="submit" form="form-product" data-toggle="tooltip" title="Save" class="btn btn-primary"><i class="fa fa-save"></i></button>
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Product</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Sort order images Product</h3>
      </div>
      <div class="panel-body" style="margin-top: 20px">
        <form action="/product/new" method="post" enctype="multipart/form-data" id="form-product" class="form-horizontal">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <ul class="nav nav-tabs">
            <li class="active"><a href="#tab-data" data-toggle="tab">General</a></li>
          </ul>
          <div class="tab-content" style="margin-top: 15px">
            <div class="tab-pane active" id="tab-data">

              <div id="simpleList" class="list-group">
              	<div class="list-group-item">This is <a href="http://rubaxa.github.io/Sortable/">Sortable</a></div>
              	<div class="list-group-item">It works with Bootstrap...</div>
              	<div class="list-group-item">...out of the box.</div>
              	<div class="list-group-item">It has support for touch devices.</div>
              	<div class="list-group-item">Just drag some elements around.</div>
              </div>

            </div>
          </div>
        </form>
      </div>

    </div>
  </div>

app/views/product/_pricehigh.html.erb
<div id="addedsuccess"></div>
<div class="row products">
	<% @pricehigh.each do |c| %>
	<div class="col-md-4 col-sm-6">
		<div class="product">
			<div>
				<div class="box-image custom-box-image">
					<div class="image" id= "pimage">
						<a href="<%=product_path( c.id ) %>">
							<%product_image = ProductImage.find_by(product_id: c.id.to_s )%>
							<%if product_image.nil?%>
							<!--img src="http://c9a023018b7727eeeae9-5cb13b2b77b05284d2f5230b4c21c288.r0.cf1.rackcdn.com/uploads/nopreview.png" alt="" class="img-responsive image1"-->
							<%= image_tag("shop/no-preview.jpg", class: "img-responsive image1") %>
							<%else%>
							<img src="<%=product_image.image.url%>" class="img-responsive">
							<%end%>
						</a>
					</div>
					<div class="text custom-text-add-to-cart">
						<a href="<%= addtocartget_path( :id => c.id ) %>" data-remote="true" class="btn btn-template-main" id="addedtocartbutton"><i class="fa fa-shopping-cart"></i>Add to cart</a>
					</div>
				</div>
				<% if c.discount != 0.0%>
				<div class="ribbon sale">
					<div class="theribbon">SALE</div>
					<div class="ribbon-background"></div>
				</div>
				<%end%>
				<% if c.created_at > 10.days.ago %>
				<div class="ribbon new">
					<div class="theribbon">NEW</div>
					<div class="ribbon-background"></div>
				</div>
				<% end %>
			</div>
			<div class="text">
				<h3><%=c.name%></h3>
				<% if c.discount != 0.0%>
				<p class="price">$<%= (c.price - c.discount)%><br><del>$<%= c.price%></del></p>
				<%else%>
				<p class="price">$<%=c.price%></p>
				<%end%>
              <!-- <p style="margin-top:15px;">
                <a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
            </p> -->
        </div>
    </div>
</div>
<%end%>
</div>
<div class="col-sm-12">
	<div class="center">
		<%= will_paginate @pricehigh, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 1,previous_label: "«" , next_label: "»"%>
	</div>
</div>

app/views/product/_pricelow.html.erb
<div id="addedsuccess"></div>
<div class="row products">
	<% @pricelow.each do |c| %>
	<div class="col-md-4 col-sm-6">
		<div class="product">
			<div>
				<div class="box-image custom-box-image">
					<div class="image" id= "pimage">
						<a href="<%=product_path( c.id ) %>">
							<%product_image = ProductImage.find_by(product_id: c.id.to_s )%>
							<%if product_image.nil?%>
							<!--img src="http://c9a023018b7727eeeae9-5cb13b2b77b05284d2f5230b4c21c288.r0.cf1.rackcdn.com/uploads/nopreview.png" alt="" class="img-responsive image1"-->
							<%= image_tag("shop/no-preview.jpg", class: "img-responsive image1") %>
							<%else%>
							<img src="<%=product_image.image.url%>" class="img-responsive">
							<%end%>
						</a>
					</div>
					<div class="text custom-text-add-to-cart">
						<a href="<%= addtocartget_path( :id => c.id ) %>" data-remote="true" class="btn btn-template-main" id="addedtocartbutton"><i class="fa fa-shopping-cart"></i>Add to cart</a>
					</div>
				</div>
				<% if c.discount != 0.0%>
				<div class="ribbon sale">
					<div class="theribbon">SALE</div>
					<div class="ribbon-background"></div>
				</div>
				<%end%>
				<% if c.created_at > 10.days.ago %>
				<div class="ribbon new">
					<div class="theribbon">NEW</div>
					<div class="ribbon-background"></div>
				</div>
				<% end %>
			</div>
			<div class="text">
				<h3><%=c.name%></h3>
				<% if c.discount != 0.0%>
				<p class="price">$<%= (c.price - c.discount)%><br><del>$<%= c.price%></del></p>
				<%else%>
				<p class="price">$<%=c.price%></p>
				<%end%>
              <!-- <p style="margin-top:15px;">
                <a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
            </p> -->
        </div>
    </div>
</div>
<%end%>
</div>
<div class="col-sm-12">
	<div class="center">
		<%= will_paginate @pricelow, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 1,previous_label: "«" , next_label: "»"%>
	</div>
</div>

app/views/product/_showproducts.html.erb
<div id="addedsuccess"></div>
<div class="row products">
	<% @show_products.each do |c| %>
	<div class="col-md-4 col-sm-6">
		<div class="product">
			<div>
				<div class="box-image custom-box-image">
					<div class="image" id= "pimage">
						<a href="<%=product_path( c.id ) %>">
							<%product_image = ProductImage.find_by(product_id: c.id.to_s )%>
							<%if product_image.nil?%>
							<!--img src="http://c9a023018b7727eeeae9-5cb13b2b77b05284d2f5230b4c21c288.r0.cf1.rackcdn.com/uploads/nopreview.png" alt="" class="img-responsive image1"-->
							<%= image_tag("shop/no-preview.jpg", class: "img-responsive image1") %>
							<%else%>
							<img src="<%=product_image.image.url%>" class="img-responsive">
							<%end%>
						</a>
					</div>
					<div class="text custom-text-add-to-cart">
						<a href="<%= addtocartget_path( :id => c.id ) %>" data-remote="true" class="btn btn-template-main" id="addedtocartbutton"><i class="fa fa-shopping-cart"></i>Add to cart</a>
					</div>
				</div>
				<% if c.discount != 0.0%>
				<div class="ribbon sale">
					<div class="theribbon">SALE</div>
					<div class="ribbon-background"></div>
				</div>
				<%end%>
				<% if c.created_at > 10.days.ago %>
				<div class="ribbon new">
					<div class="theribbon">NEW</div>
					<div class="ribbon-background"></div>
				</div>
				<% end %>
			</div>
			<div class="text">
				<h3><%=c.name%></h3>
				<% if c.discount != 0.0%>
				<p class="price"><del>$<%= c.price %></del> $<%= (c.price - c.discount) %></p>
				<%else%>
				<p class="price">$<%=c.price%></p>
				<%end%>
              <!-- <p style="margin-top:15px;">
                <a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
            </p> -->
        </div>
    </div>
</div>
<%end%>
</div>
<div class="col-sm-12">
	<div class="center">
		<%= will_paginate @show_products, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 1,previous_label: "«" , next_label: "»"%>
	</div>
</div>

app/views/product/newest.js.erb
$( "#product-containter" ).html( "<%= escape_javascript( render( "newest" ) ) %>" );

app/views/product/orderimages.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "order" ) ) %>" );

app/views/product/pricehigh.js.erb
$( "#product-containter" ).html( "<%= escape_javascript( render( "pricehigh" ) ) %>" );

app/views/product/pricelow.js.erb
$( "#product-containter" ).html( "<%= escape_javascript( render( "pricelow" ) ) %>" );

app/views/product/showall.js.erb
$( "#product-containter" ).html( "<%= escape_javascript( render( "showproducts" ) ) %>" );